# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('Permissions', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexBanerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('a', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('p', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexBullhornInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('publisher', models.CharField(max_length=30)),
                ('times', models.CharField(max_length=20)),
                ('a_link', models.CharField(max_length=100)),
                ('sort_id', models.SmallIntegerField(null=True)),
                ('hot_id', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('a_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndexMovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('a', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessageNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageNum', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=30)),
                ('uptime', models.CharField(max_length=30)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=50)),
                ('MenuTree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HPAdmin.MenuTree')),
            ],
        ),
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(default='123456', max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(null=True)),
                ('DoManage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HPAdmin.DoManage')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoManage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HPAdmin.DoManage')),
                ('UserManage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HPAdmin.UserManage')),
            ],
        ),
    ]
