# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('a', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('p', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexBullhornInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('publisher', models.CharField(max_length=30)),
                ('times', models.CharField(max_length=20)),
                ('a_link', models.CharField(max_length=100)),
                ('sort_id', models.SmallIntegerField(null=True)),
                ('hot_id', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('a_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndexMovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('a', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
