# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='xh',
            new_name='hullhornxh',
        ),
    ]
