# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=30)),
                ('uptime', models.CharField(max_length=30)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsDate',
        ),
    ]
