# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
