# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanage',
            name='Relopermissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HPAdmin.Relopermissions'),
        ),
    ]
