# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='Permissions',
        ),
        migrations.AddField(
            model_name='userrole',
            name='Relopermissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HPAdmin.Relopermissions'),
        ),
        migrations.AlterField(
            model_name='relopermissions',
            name='Permissions',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
