# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbanerinfo',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
