# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0002_domanage_relopermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageNum', models.IntegerField(max_length=8)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
