# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0002_auto_20171110_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relopermissions',
            name='MenuTree',
        ),
        migrations.AddField(
            model_name='relopermissions',
            name='DoManage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HPAdmin.DoManage'),
        ),
    ]
