# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0002_usermanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
    ]
