# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0002_indexbanerinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbanerinfo',
            name='p',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indexbanerinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indexmovieinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
