# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0003_auto_20170920_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBullhornInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=100)),
                ('p', models.CharField(max_length=100)),
                ('fbadmin', models.CharField(max_length=30)),
                ('bhtime', models.CharField(max_length=20)),
                ('a', models.CharField(max_length=100)),
                ('x', models.SmallIntegerField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
