# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0003_messagenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenum',
            name='MessageNum',
            field=models.IntegerField(),
        ),
    ]
