# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0004_indexbullhorninfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='a',
            new_name='a_link',
        ),
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='p',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='status',
            new_name='hot_id',
        ),
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='fbadmin',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='x',
            new_name='sort_id',
        ),
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='bhtime',
            new_name='times',
        ),
    ]
