# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0005_auto_20170928_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbullhorninfo',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
