# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0006_auto_20170928_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='times',
            new_name='t',
        ),
    ]
