# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0006_auto_20170928_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('a_link', models.CharField(max_length=100)),
            ],
        ),
    ]
