# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0008_auto_20170928_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='c',
            new_name='beijin',
        ),
    ]
