# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPAdmin', '0013_auto_20170928_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexbullhorninfo',
            old_name='cc',
            new_name='d',
        ),
    ]
